### ISSUE TITLE
release plans ?

### ISSUE THREAD

**Issue by kapouer** [andrewlow/v8z#11]
Hi,

i wonder if we're gonna see upstream v8 support s390(x).
This is interesting because:
https://buildd.debian.org/status/package.php?p=nodejs&suite=unstable

thanks for any info !

**Comment by mhdawson** [comment]
We do want to get there just like we did for PPC.  We are still working on upstreaming to bleeding edge where we can start to contribute the changes back.  We hope to start contributing the changes back to google in about 2 months.  There is more work once this starts:

+  there will be a review cycle with google so it will likely take a few months to complete the contribution
+  and once v8 supports s390(x) we need Node to pick up the version the supported version. Currently this should happen twice a year.  
+ we'll need to get Node specific changes into the community repos (we are Node contributors so I don't see any problem doing this, just work that needs to take place after Node picks up the newer V8)

So we are actively working on it but will take a little longer before we get there

**Comment by kapouer** [comment]
Thank you for the information.
For debian it means "not next release, but probably the one after" - which is good news,
because nodejs will then be able to run on all architectures supported by debian.

**Comment by kapouer** [comment]
On the other hand, i just built nodejs 4.1.2 with your 4.5 branch on https://db.debian.org/machines.cgi?host=zelenka, and Node continuous integration tests pass successfully (well, almost, but the three failing tests are failing on other arches as well so it's probably unrelated)...
So is it a bad idea to build nodejs 4.1.2 on s390x in debian ? Is it under v8 BSD-3-Clause license ? Is there a specific copyright to mention ?
It's tempting to get an "all green" here https://buildd.debian.org/status/package.php?p=nodejs&suite=sid

**Comment by mhdawson** [comment]
We are working on exactly want you want here:  https://github.com/andrewlow/node

on the v4.x-port branch.  

In terms of the licence I'll need to get the right person to comment on that but I don't think there will be an issue with using it for the debian builds if you want to do that.

So I'd suggest that you pull/build from there as we'll be making any updates there that are needed to support the IBM node 4.x builds for 4.X

**Comment by kapouer** [comment]
Fantastic ! I actually did the merge-v8-and-patch-node myself yesterday, and got a running s390x build of nodejs 4.1.2 on debian/experimental, with passing test-ci.
I'll make sure commits from your branch are not missing.
On debian we have less things to worry about - libuv is packaged independently, openssl too, but for now we're keeping v8 embedded.
Also if i read you correctly, you'll provide some sort of security fixes for upcoming LTS Node.js 4.2 ?

**Comment by Paul-Ivinson** [comment]
Our contributions are under the same license as the receiving repo (v8 BSD-3-Clause for V8 and MIT for Node.js). Copyright remains with IBM but this should already be included in the correct places or IBM is named as a contributor. In short, neither licenses not copyright should cause you problems. HTH.

**Comment by mhdawson** [comment]
The v4.x-port branch will be updated to match 4.2 when it comes out
