### ISSUE TITLE
"make s390x" doesn't work out of the box because a variable is set but not used. (-Werror=unused-but-set-variable in affect)

### ISSUE THREAD

**Issue by maximmai** [andrewlow/v8z#9]
../src/s390/lithium-codegen-s390.cc: In member function ‘void v8::internal::LCodeGen::DoModI(v8::internal::LModI*)’:
../src/s390/lithium-codegen-s390.cc:894:12: error: variable ‘scratch’ set but not used [-Werror=unused-but-set-variable]
   Register scratch = scratch0();
            ^
cc1plus: all warnings being treated as errors
make[1]: *** [/sandbox/maximmai/src/v8z/out/s390x.release/obj.target/v8_base/src/s390/lithium-codegen-s390.o] Error 1
make[1]: Leaving directory `/sandbox/maximmai/src/v8z/out'
make: *** [s390x.release] Error 2

**Comment by mdawsonibm** [comment]
Thanks for the heads up, we are looking into it. 

Can we get the specific info as to what level of the compiler you are using ?

**Comment by joransiu** [comment]
Hi @maximmai, this issue was fixed on our 3.14-s390 branch recently.   I have pushed the commit to master branch.  Please give it a try again.  Thanks! https://github.com/andrewlow/v8z/commit/84f38ae88da5876e13db5cf938c0afd1c2a5f571

**Comment by joransiu** [comment]
For reference, this issue was reproducible using GCC 4.8

**Comment by maximmai** [comment]
Verified with the latest code. Closing off this issue now. Thanks for the fix.
